---
# What: Configure the SSH server
#
- name: 'Include OS specific variables'
  ansible.builtin.include_vars: "{{ ansible_facts['os_family'] }}.yml"
  no_log: true

- name: 'Install SSH server'
  ansible.builtin.package:
    name: 'openssh-server'
    state: 'present'
  notify:
    - 'Restart sshd'

- name: 'Flush handlers'
  ansible.builtin.meta: 'flush_handlers'

- name: 'Create conf directory'
  ansible.builtin.file:
    dest: '/etc/ssh/conf.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0700'

- name: 'Place/remove base config file'
  ansible.builtin.template:
    dest: '/etc/ssh/conf.d/00_sshd_base'
    src: '00_sshd_base.j2'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'Place additional config file(s)'
  ansible.builtin.copy:
    dest: "/etc/ssh/conf.d/{{ file }}"
    src: "{{ sshd_configdir + file }}"
    owner: 'root'
    group: 'root'
    mode: '0640'
  loop: "{{ sshd_configs | default([]) }}"
  loop_control:
    loop_var: 'file'
  when: sshd_configs | length > 0

- name: 'Crypto policy file equals sshd_config settings. Also a dirty hack for the mean time'
  ansible.builtin.template:
    dest: '/usr/share/crypto-policies/DEFAULT/opensshserver.txt' # this file (/etc/crypto-policies/back-ends/opensshserver.config) links to the default policy at this time. this should be variable depending on crypto policy setting.
    src: 'opensshserver.config.j2'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 8 
  notify:
    - 'Restart sshd'

- name: 'Merge configs and restart SSHD'
  ansible.builtin.assemble:
    dest: '{{ sshd_dest_config_file }}'
    src: '/etc/ssh/conf.d'
    owner: 'root'
    group: 'root'
    mode: '0600'
    validate: '/usr/sbin/sshd -t -f %s'
  notify:
    - 'Restart sshd'

- name: 'Setup SSH keys'
  ansible.builtin.include_tasks: 'deploy_ssh_keys.yml'
